# CFLAGS=-pedantic -Wall -Werror -ggdb3
# PROGS= cyoa-step2  #cyoa-step1 cyoa-step3 cyoa-step4
# all: $(PROGS)
# cyoa-step%: cyoa-step%.o Page.hpp Story.hpp
# 	g++ -o $@ $^
# %.o: %.cpp
# 	g++ $(CFLAGS) -c $<

# .PHONY: clean
# clean:
# 	rm -f *~ $(PROGS) $(OBJS)

# cyoa-step1:
# 	g++ cyoa-step1.cpp -o cyoa-step1

# cyoa-step2:
# 	g++ cyoa-step2.cpp -o cyoa-step2

# cyoa-step3:
# 	g++ cyoa-step3.cpp -o cyoa-step3

# cyoa-step4:
# 	g++ cyoa-step4.cpp -o cyoa-step4
